# Generated by Django 3.1.7 on 2021-03-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password1', models.CharField(max_length=50, verbose_name='Password')),
                ('password2', models.CharField(max_length=50, verbose_name='Re-Password')),
            ],
            options={
                'verbose_name': 'User_account',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
