# Generated by Django 3.1.7 on 2021-03-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User_account', 'verbose_name_plural': 'User_accounts'},
        ),
    ]
