# Generated by Django 3.1.7 on 2021-03-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210320_0613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
