# Generated by Django 3.1.7 on 2021-04-05 12:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210405_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
